### ISSUE TITLE
Navbar redesign

### ISSUE THREAD

**Issue by tsukii21** [GeekHaven/Geektoberfest-Main#71]
The navbar is back to being non-sticky due to latest redesign commits. Also the brand is somewhat smaller than the links. They should be of equal size or the other way around. Also the current effect on hover is somewhat subtle. All these should be fixed without changing the current structure and functionality of the element

**Comment by Codedude1** [comment]
I want to work on this

**Comment by tsukii21** [comment]
Go ahead

**Comment by Cypherdious89** [comment]
@tsukii21 Actually I have fixed that while solving my issue. 😅
I even created a PR but closed that due to some merge conflicts caused due to adding smooth scrolling feature. Creating another one in about an hour or so.

**Comment by tsukii21** [comment]
@Priyansh-09 You have fixed all of my mentioned issues? And did you pull the latest changes?

**Comment by Cypherdious89** [comment]
> 
> 
> @Priyansh-09 You have fixed all of my mentioned issues? And did you pull the latest changes?

I created a PR with fixing all these issues but there was some merge conflicts due to PR that added smooth scroll feature. Creating a new one in just a few minutes

**Comment by Cypherdious89** [comment]
@tsukii21 I have made the all the design changes that you have mentioned in PR #73.
Here's the GitHub live page link - https://priyansh-09.github.io/Geektoberfest-Main/
Please review this.

**Comment by sggts04** [comment]
@Codedude1 Priyansh has solved some of the issues but the nav is still not sticky and can definitely use some cool hover effect. Make sure to update your fork to the latest version of this repo before making new changes.

**Comment by Codedude1** [comment]
Okay Sure. Thanks.

**Comment by tsukii21** [comment]
@Codedude1 The mentioned issues are fixed but since the navbar is hovering above and the entire page is pushed upwards to take the space of the previously non-sticky navbar, smooth scroll navigation is ending up in cropped sections. Fix this issue.

**Comment by sggts04** [comment]
For example:
![image](https://user-images.githubusercontent.com/20678047/95829930-8c77af80-0d54-11eb-8498-7d2b883cea7b.png)

Clicking on Projects leads me to here, it assumes there is no navbar there and shows cropped up. Ideally the section should appear below the navbar

**Comment by Cypherdious89** [comment]
> 
> 
> @Codedude1 The mentioned issues are fixed but since the Navbar is hovering above and the entire page is pushed upwards to take the space of the previously non-sticky Navbar, smooth scroll navigation is ending up in cropped sections. Fix this issue.

I will fix this while Re-designing footer for the page ( Issue #83 ).

@Codedude1 is facing some problems currently.

**Comment by Codedude1** [comment]
Thanks, @Priyansh-09. I'm doing some urgent work rn.

**Comment by tsukii21** [comment]
Cool. I am closing this issue.
